DROP TABLE IF EXISTS Items;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS ProductCategories;
DROP TABLE IF EXISTS Suppliers;
CREATE TABLE Orders (Id INTEGER NOT NULL, TotalPrice REAL, clientFullName TEXT, clientAdress INTEGER);
CREATE TABLE ProductCategories(id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name TEXT, department TEXT, description TEXT);
CREATE TABLE Products(id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name TEXT, price NUMERIC, description TEXT, currency TEXT, id_productCategory INTEGER, id_supplier INTEGER);
CREATE TABLE Suppliers(id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name TEXT, description TEXT);
CREATE TABLE Items (Id INTEGER NOT NULL, BasketId INTEGER NOT NULL, IdProduct INTEGER NOT NULL, Quantity INTEGER NOT NULL);
INSERT INTO Products (name, price, description, currency, id_productCategory, id_supplier) VALUES ('Ball', 12, 'ball description', 'PLN', 1, 1);
INSERT INTO Products (name, price, description, currency, id_productCategory, id_supplier) VALUES ('Backet', 23, 'jacket description', 'PLN', 2, 2);
INSERT INTO Products (name, price, description, currency, id_productCategory, id_supplier) VALUES ('Flower', 34, 'flower description', 'PLN', 3, 3);
INSERT INTO Products (name, price, description, currency, id_productCategory, id_supplier) VALUES ('Rocket', 234, 'rocket  description', 'PLN', 1, 1);
INSERT INTO Products (name, price, description, currency, id_productCategory, id_supplier) VALUES ('Swimsuit', 23.5, 'swimsiut description', 'PLN', 1, 1);
INSERT INTO Products (name, price, description, currency, id_productCategory, id_supplier) VALUES ('Bike', 1002.25, 'bike description', 'PLN', 1, 4);
INSERT INTO Products (name, price, description, currency, id_productCategory, id_supplier) VALUES ('Helmet', 321, 'helmet description', 'PLN', 1, 4);
INSERT INTO Products (name, price, description, currency, id_productCategory, id_supplier) VALUES ('Tv', 2030.2, 'tv description', 'PLN', 4, 5);
INSERT INTO Products (name, price, description, currency, id_productCategory, id_supplier) VALUES ('Radio', 219, 'radio description', 'PLN', 4, 5);
INSERT INTO Products (name, price, description, currency, id_productCategory, id_supplier) VALUES ('Mixer', 312, 'mixer description', 'PLN', 5, 5);
INSERT INTO Products (name, price, description, currency, id_productCategory, id_supplier) VALUES ('Plate', 0.5, 'dish description', 'PLN', 5, 3);
INSERT INTO Products (name, price, description, currency, id_productCategory, id_supplier) VALUES ('Glass', 0.99, 'glass description', 'PLN', 5, 5);
INSERT INTO Products (name, price, description, currency, id_productCategory, id_supplier) VALUES ('Trousers', 201.23, 'trousers description', 'PLN', 2, 2);
INSERT INTO Products (name, price, description, currency, id_productCategory, id_supplier) VALUES ('Golden calf', 15231, 'goldent calf description', 'PLN', 3, 5);
INSERT INTO Products (name, price, description, currency, id_productCategory, id_supplier) VALUES ('Hat', 68.99, 'hat description', 'PLN', 2, 1);
INSERT INTO ProductCategories (name, department, description) VALUES ('Sport', 'sport department', 'sport description');
INSERT INTO ProductCategories (name, department, description) VALUES ('Clothing', 'clothing department', 'clothing description');
INSERT INTO ProductCategories (name, department, description) VALUES ('Home', 'home department', 'home description');
INSERT INTO ProductCategories (name, department, description) VALUES ('Rtv', 'rtv department', 'rtv description');
INSERT INTO ProductCategories (name, department, description) VALUES ('Agd', 'agd department', 'agd description');
INSERT INTO Suppliers (name, description) VALUES ('Nike', 'Nike description');
INSERT INTO Suppliers (name, description) VALUES ('H&M', 'H&M description');
INSERT INTO Suppliers (name, description) VALUES ('Ikea', 'Ikea description');
INSERT INTO Suppliers (name, description) VALUES ('Giant', 'Giant description');
INSERT INTO Suppliers (name, description) VALUES ('Alfa', 'Alfa description');